name: webui
description: A simple AngularDart app
version: 0.0.1
homepage: https://github.com/DevAlves1993/OurOSms
author: Christian Amani

environment:
  sdk: ^1.23.0

dependencies:
  angular2: ^3.0.0
  angular_components: ^0.5.1
  http: ^0.11.0
  logging: ^0.11.3+1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
